# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: carrier_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'carrier_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63\x61rrier_list.proto\x12\x12\x63om.google.carrier\"o\n\tCarrierId\x12\x0f\n\x07mcc_mnc\x18\x01 \x01(\t\x12\r\n\x03spn\x18\x02 \x01(\tH\x00\x12\x0e\n\x04imsi\x18\x03 \x01(\tH\x00\x12\x0e\n\x04gid1\x18\x04 \x01(\tH\x00\x12\x0f\n\x05iccid\x18\x06 \x01(\tH\x00\x42\x0b\n\tmvno_dataJ\x04\x08\x05\x10\x06\"]\n\nCarrierMap\x12\x16\n\x0e\x63\x61nonical_name\x18\x01 \x01(\t\x12\x31\n\ncarrier_id\x18\x02 \x03(\x0b\x32\x1d.com.google.carrier.CarrierIdJ\x04\x08\x03\x10\x04\"M\n\x0b\x43\x61rrierList\x12-\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x1e.com.google.carrier.CarrierMap\x12\x0f\n\x07version\x18\x02 \x01(\x03\x42\x15\x42\x11\x43\x61rrierListProtosP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carrier_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\021CarrierListProtosP\001'
  _globals['_CARRIERID']._serialized_start=42
  _globals['_CARRIERID']._serialized_end=153
  _globals['_CARRIERMAP']._serialized_start=155
  _globals['_CARRIERMAP']._serialized_end=248
  _globals['_CARRIERLIST']._serialized_start=250
  _globals['_CARRIERLIST']._serialized_end=327
# @@protoc_insertion_point(module_scope)
